In [ ]:
import pandas as pd
df = pd.read_excel("/content/Dataset for Data Analytics.xlsx")
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [ ]:
df['CouponCode'] = df['CouponCode'].fillna('No Coupon')
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [ ]:
print("Shape of the Data set after removing the duplicates:", df.shape)

Shape of the Data set after removing the duplicates: (1200, 14)

In [ ]:
print('Filling missing values for numeric values:')
df.fillna(df.mean(numeric_only = True), inplace=True)
print(df)

Filling missing values for numeric values:
        OrderID       Date CustomerID  Product  Quantity  UnitPrice  \
0     ORD200000 2023-01-04     C72649  Monitor         5     570.62
1     ORD200001 2024-08-23     C75739    Phone         2     151.35
2     ORD200002 2024-02-27     C81728   Tablet         5     550.68
3     ORD200003 2023-10-15     C33540    Chair         1     273.19
4     ORD200004 2025-05-08     C81840  Printer         4     626.01
...         ...        ...        ...      ...       ...        ...
1195  ORD201195 2024-06-20     C21126     Desk         1     107.04
1196  ORD201196 2024-03-04     C20095  Monitor         2     662.53
1197  ORD201197 2023-07-13     C79674   Tablet         2     436.84
1198  ORD201198 2024-08-22     C64753    Chair         4     262.52
1199  ORD201199 2023-06-11     C57502   Tablet         4     560.58

     ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0        928 Main St    Debit Card     Shipped    TRK37947903            7
1        823 Main St        Online     Shipped    TRK91186779            3
2        512 Main St   Credit Card   Cancelled    TRK42903982            8
3        275 Main St    Debit Card    Returned    TRK62788070            5
4        668 Main St        Online   Delivered    TRK29241424            8
...              ...           ...         ...            ...          ...
1195     392 Main St   Credit Card   Cancelled    TRK38009181            6
1196     778 Main St        Online   Cancelled    TRK69207593            5
1197     275 Main St        Online   Delivered    TRK88039356            2
1198     509 Main St    Debit Card   Cancelled    TRK71683331            4
1199     201 Main St     Gift Card    Returned    TRK51116746            6

     CouponCode ReferralSource  TotalPrice
0        SAVE10      Instagram     2853.10
1        SAVE10       Referral      302.70
2      FREESHIP          Email     2753.40
3        SAVE10       Facebook      273.19
4        SAVE10          Email     2504.04
...         ...            ...         ...
1195   FREESHIP         Google      107.04
1196  No Coupon       Facebook     1325.06
1197   FREESHIP      Instagram      873.68
1198   WINTER15      Instagram     1050.08
1199     SAVE10       Referral     2242.32

[1200 rows x 14 columns]

In [ ]:
print('checking data types:')
df.dtypes

checking data types:

OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

In [ ]:
print("save cleaned dataset:")
df.to_excel('cleaned_dataset.xlsx', index=False)

save cleaned dataset:

In [ ]:
print("Download cleaned file:")
from google.colab import files
files.download('cleaned_dataset.xlsx')

Download cleaned file: