In [3]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.49)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2026.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=5160d29945698de1e262d33272e5144d7facbf7674d47734261fab4537c4eafc
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [5]:
import pandas as pd
from pandasql import sqldf
df = pd.read_excel("/content/Dataset for Data Analytics (1).xlsx")
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [6]:
print("creating a SQL Function:")
pysqldf = lambda q: sqldf(q, globals())

creating a SQL Function:

In [7]:
print("using SELECT Query: ")
query = """ SELECT CustomerID, Product, Totalprice FROM df """
pysqldf(query)

using SELECT Query:

     CustomerID  Product  TotalPrice
0        C72649  Monitor     2853.10
1        C75739    Phone      302.70
2        C81728   Tablet     2753.40
3        C33540    Chair      273.19
4        C81840  Printer     2504.04
...         ...      ...         ...
1195     C21126     Desk      107.04
1196     C20095  Monitor     1325.06
1197     C79674   Tablet      873.68
1198     C64753    Chair     1050.08
1199     C57502   Tablet     2242.32

[1200 rows x 3 columns]

In [10]:
print("Using WHERE Clause:")
query1 = """ SELECT * FROM df WHERE TotalPrice > 500 """
pysqldf(query1)

Using WHERE Clause:

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00.000000,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200002,2024-02-27 00:00:00.000000,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
2,ORD200004,2025-05-08 00:00:00.000000,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
3,ORD200006,2025-06-17 00:00:00.000000,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
4,ORD200007,2023-05-12 00:00:00.000000,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812,ORD201194,2023-11-19 00:00:00.000000,C29885,Printer,3,189.44,725 Main St,Cash,Pending,TRK62067865,4,FREESHIP,Email,568.32
813,ORD201196,2024-03-04 00:00:00.000000,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,None,Facebook,1325.06
814,ORD201197,2023-07-13 00:00:00.000000,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
815,ORD201198,2024-08-22 00:00:00.000000,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
816,ORD201199,2023-06-11 00:00:00.000000,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [11]:
print("To sort values from highest to lowest using ORDER BY:")
query2 = """ SELECT Product, TotalPrice FROM df ORDER BY TotalPrice DESC """
pysqldf(query2)

To sort values from highest to lowest using ORDER BY:

      Product  TotalPrice
0      Tablet     3456.40
1     Monitor     3390.95
2      Laptop     3390.80
3       Chair     3384.90
4      Tablet     3370.20
...       ...         ...
1195   Laptop       18.20
1196   Tablet       17.98
1197   Tablet       17.24
1198    Phone       14.06
1199    Phone       11.39

[1200 rows x 2 columns]

In [12]:
print("Using GROUP BY:")
query3 = """ SELECT PaymentMethod, COUNT(*) as TotalOrders FROM df GROUP BY PaymentMethod """
pysqldf(query3)

Using GROUP BY:

  PaymentMethod  TotalOrders
0          Cash          246
1   Credit Card          234
2    Debit Card          232
3     Gift Card          230
4        Online          258

In [13]:
print("SUM Aggregation:")
query4 = """ SELECT Product, SUM(TotalPrice) as TotalSales FROM df GROUP BY Product """
pysqldf(query4)

SUM Aggregation:

   Product  TotalSales
0    Chair   195620.11
1     Desk   167459.93
2   Laptop   192126.56
3  Monitor   175651.41
4    Phone   151722.39
5  Printer   195612.61
6   Tablet   186568.95

In [14]:
print(" Average (AVG) Aggregation:")
query5 = """ SELECT Product, AVG(TotalPrice) as AverageSales FROM df GROUP BY Product """
pysqldf(query5)

 Average (AVG) Aggregation:

   Product  AverageSales
0    Chair   1098.989382
1     Desk    985.058412
2   Laptop   1110.558150
3  Monitor   1077.616012
4    Phone    972.579423
5  Printer   1080.732652
6   Tablet   1042.284637

In [15]:
print("using COUNT Aggregation:")
query6 = """ SELECT COUNT(*) as TotalOrders FROM df """
pysqldf(query6)

using COUNT Aggregation:

   TotalOrders
0         1200